# Generated by Django 3.2.7 on 2021-10-01 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('sellerAddress', models.CharField(blank=True, max_length=256, null=True)),
                ('title', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField(null=True)),
                ('image', models.ImageField(null=True, upload_to='media')),
                ('descriptiveText', models.TextField()),
                ('publicDate', models.DateTimeField(auto_now_add=True)),
                ('endDate', models.DateTimeField()),
                ('bidderAddress', models.CharField(max_length=256, null=True)),
                ('lbidderAddress', models.JSONField(default=list)),
                ('bid', models.IntegerField(null=True)),
                ('hash', models.CharField(max_length=32)),
                ('txId', models.CharField(max_length=66)),
                ('lastBidder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lastBid', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
