# Generated by Django 3.2.7 on 2021-09-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='priceInToken',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
