# Generated by Django 3.2.7 on 2021-09-29 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_remove_auction_priceintoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='sellerAddress',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
