# Generated by Django 3.2.7 on 2021-09-29 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_auction_selleraddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='sellerAddress',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
